import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Full vehicle database - 1330 vehicles parsed from PVO_Square_Footage_List_2020.xlsx
// Generated by parse-vehicles.cjs from src/data/parsed-vehicles-full.txt
import vehicleData from "./vehicles.json" with { type: "json" };

interface VehicleRecord {
  make: string;
  model: string;
  year_start: number;
  year_end: number;
  side_sqft: number;
  back_sqft: number;
  hood_sqft: number;
  roof_sqft: number;
  total_sqft: number;
  corrected_sqft: number;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(SUPABASE_URL, SERVICE_ROLE);

    // Parse request body for options
    let forceReseed = false;
    try {
      const body = await req.json();
      forceReseed = body?.force === true;
    } catch {
      // No body or invalid JSON is fine
    }

    // Check current count
    const { count: existingCount } = await supabase
      .from("vehicle_dimensions")
      .select("*", { count: "exact", head: true });

    // Only skip if we have 1000+ vehicles AND not forcing
    if (!forceReseed && existingCount && existingCount > 1000) {
      return new Response(
        JSON.stringify({
          message: `Database already has ${existingCount} vehicles. Use {"force": true} to reseed.`,
          existing_count: existingCount
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const vehicles = vehicleData as VehicleRecord[];
    console.log(`[SeedVehicles] Loaded ${vehicles.length} vehicles from JSON`);

    // If force reseed, clear existing data first
    if (forceReseed && existingCount && existingCount > 0) {
      console.log('[SeedVehicles] Force reseed - clearing existing data...');
      const { error: deleteError } = await supabase
        .from("vehicle_dimensions")
        .delete()
        .neq('id', '00000000-0000-0000-0000-000000000000'); // Delete all

      if (deleteError) {
        console.error('[SeedVehicles] Delete error:', deleteError);
      } else {
        console.log('[SeedVehicles] Cleared existing vehicles');
      }
    }

    // Insert vehicles in batches
    const batchSize = 100;
    let inserted = 0;
    let errors = 0;

    for (let i = 0; i < vehicles.length; i += batchSize) {
      const batch = vehicles.slice(i, i + batchSize);

      const { error } = await supabase.from("vehicle_dimensions").insert(batch);

      if (error) {
        console.error(`Batch ${Math.floor(i / batchSize)} error:`, error);
        errors++;
      } else {
        inserted += batch.length;
        console.log(`[SeedVehicles] Inserted batch ${Math.floor(i / batchSize) + 1}, total: ${inserted}`);
      }
    }

    // Verify final count
    const { count: finalCount } = await supabase
      .from("vehicle_dimensions")
      .select("*", { count: "exact", head: true });

    // Check for a specific vehicle to verify
    const { data: malibuCheck } = await supabase
      .from("vehicle_dimensions")
      .select("make, model, year_start, year_end, total_sqft, roof_sqft")
      .eq("make", "Chevrolet")
      .ilike("model", "%Malibu%")
      .limit(3);

    return new Response(
      JSON.stringify({
        success: true,
        message: `Seeded ${inserted} vehicles into vehicle_dimensions table`,
        source: "parsed-vehicles-full.txt (1330 vehicles)",
        parsed_count: vehicles.length,
        inserted_count: inserted,
        final_count: finalCount,
        batch_errors: errors,
        sample_vehicles: malibuCheck
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (err) {
    console.error("Seed error:", err);
    return new Response(
      JSON.stringify({ error: String(err) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
