-- Add missing columns to ai_creatives for Creative Vault system
ALTER TABLE public.ai_creatives 
ADD COLUMN IF NOT EXISTS tool_slug text,
ADD COLUMN IF NOT EXISTS format_slug text,
ADD COLUMN IF NOT EXISTS brand text,
ADD COLUMN IF NOT EXISTS channel text,
ADD COLUMN IF NOT EXISTS platform text;

-- Create creative_tags table
CREATE TABLE IF NOT EXISTS public.creative_tags (
  slug text PRIMARY KEY,
  category text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now()
);

-- Create creative_tag_map junction table
CREATE TABLE IF NOT EXISTS public.creative_tag_map (
  creative_id uuid REFERENCES public.ai_creatives(id) ON DELETE CASCADE,
  tag_slug text REFERENCES public.creative_tags(slug) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (creative_id, tag_slug)
);

-- Enable RLS
ALTER TABLE public.creative_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creative_tag_map ENABLE ROW LEVEL SECURITY;

-- RLS for creative_tags (read-only for authenticated users)
CREATE POLICY "Anyone can read creative tags"
ON public.creative_tags FOR SELECT
USING (true);

-- RLS for creative_tag_map (org-based access via ai_creatives)
CREATE POLICY "Users can manage tags for their org creatives"
ON public.creative_tag_map FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.ai_creatives ac
    WHERE ac.id = creative_tag_map.creative_id
    AND ac.organization_id = public.get_user_organization_id()
  )
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_ai_creatives_tool_slug ON public.ai_creatives(tool_slug);
CREATE INDEX IF NOT EXISTS idx_ai_creatives_format_slug ON public.ai_creatives(format_slug);
CREATE INDEX IF NOT EXISTS idx_ai_creatives_brand ON public.ai_creatives(brand);
CREATE INDEX IF NOT EXISTS idx_ai_creatives_platform ON public.ai_creatives(platform);
CREATE INDEX IF NOT EXISTS idx_creative_tag_map_tag ON public.creative_tag_map(tag_slug);

-- Seed standard tags (idempotent)
INSERT INTO public.creative_tags (slug, category, description) VALUES
('source:mighty_task', 'source', 'Generated from MightyTask'),
('source:content_calendar', 'source', 'Generated from Content Calendar'),
('source:noah_prompt', 'source', 'Generated by Noah prompts/agent'),
('source:manual', 'source', 'Manual creation'),
('source:youtube', 'source', 'Generated from YouTube'),
('source:inspiration', 'source', 'Generated from Inspiration'),
('source:producer_job', 'source', 'Generated from Producer Job'),
('tool:multi_clip_reel', 'tool', 'Multi-Clip Reel Builder'),
('tool:auto_split', 'tool', 'Auto-Split Engine'),
('tool:static_creator', 'tool', 'Static/Carousel Creator'),
('tool:content_atomizer', 'tool', 'Content Atomizer'),
('tool:youtube_editor', 'tool', 'YouTube AI Editor'),
('tool:inspo_scrubber', 'tool', 'Inspiration Hub'),
('tool:mighty_edit', 'tool', 'MightyEdit'),
('format:reel', 'format', 'Reel'),
('format:story', 'format', 'Story'),
('format:short', 'format', 'Short'),
('format:static', 'format', 'Static'),
('format:carousel', 'format', 'Carousel'),
('status:draft', 'status', 'Draft'),
('status:rendering', 'status', 'Rendering'),
('status:complete', 'status', 'Complete'),
('status:failed', 'status', 'Failed')
ON CONFLICT (slug) DO NOTHING;